version: 1
id: lung-room-acc5b4
name: Lung Room
type: room
locationId: kolole-fc20d0
targetTempC: 22
targetHumidity: 50
emergencyTempC: 35
devices:
    - id: e71d14d9-6fac-461b-87a3-d8c7e52a65d6
      name: Xiaomi LYWSD03MMC (Mijia BLE)
      capabilities:
        - id: humidity-1321d0
          kind: sensor
          name: Humidity
          entity: sensor.bte_88b0_humidity
          measurement: humidity
        - id: temperature-60b08a
          kind: sensor
          name: Temperature
          entity: sensor.bte_88b0_temperature
          measurement: temperature
